name: twirp_dart_core
description: Core library for using Twirp + Dart
version: 1.0.0+2
homepage: https://github.com/apptreesoftware/twirp_dart_core

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
dev_dependencies:
  test: ^1.0.0
